"""drop english_meaning from vocab tables

Revision ID: b6081f067a99
Revises: d0ab5a61c11f
Create Date: 2026-05-19 21:25:11.848608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6081f067a99'
down_revision: Union[str, Sequence[str], None] = 'd0ab5a61c11f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('known_vocab', 'english_meaning')
    op.drop_column('want_to_learn', 'english_meaning')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('want_to_learn', sa.Column('english_meaning', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('known_vocab', sa.Column('english_meaning', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
