name: Basic CI
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - name: Install Python
        run: uv python install
      - name: Install dependencies
        run: uv sync
        working-directory: ./backend
      - name: Run tests
        run: uv run pytest
        working-directory: ./backend